import { test, expect, type APIRequestContext } from '@playwright/test'
import { randomUUID } from 'node:crypto'
import { readFile, mkdir } from 'node:fs/promises'
import { resolve } from 'node:path'

const data = () => ({ nodeData: { id: 'root', topic: '阅读示例', children: [
  { id: 'a', topic: '核心观点', expanded: false, children: [{ id: 'a1', topic: '隐藏事实', metadata: { kind: 'fact', sources: [{ document: '样例.md', section: '一', quote: '引用原文' }] } }] },
  { id: 'b', topic: '实施方法' },
] }, direction: 1, arrows: [], summaries: [] })
async function get(request: APIRequestContext) { return (await request.get('/api/document')).json() }
async function edit(request: APIRequestContext, operations: unknown[]) {
  const doc = await get(request)
  const response = await request.post('/api/operations', { data: { documentId: doc.documentId, baseRevision: doc.revision, requestId: randomUUID(), operations, actor: 'codex-test' } })
  expect(response.ok()).toBeTruthy()
  return response.json()
}
test.beforeEach(async ({ request }) => {
  const doc = await get(request)
  const response = await request.post('/api/document', { data: { documentId: doc.documentId, baseRevision: doc.revision, requestId: randomUUID(), data: data() } })
  expect(response.ok()).toBeTruthy()
})

test('human editing saves stable IDs and reload restores text; Tab add and undo work', async ({ page, request }) => {
  await page.goto('/')
  const root = page.locator('[data-nodeid="meroot"]')
  await root.dblclick({ delay: 70 })
  await page.locator('#input-box').fill('人工修改的主题')
  await page.locator('#input-box').press('Enter')
  await expect.poll(async () => (await get(request)).data.nodeData.topic).toBe('人工修改的主题')
  await expect(page.locator('#save-status')).toHaveText('已保存到本机')
  await page.reload()
  await expect(root).toContainText('人工修改的主题')
  await root.click()
  await page.keyboard.press('Tab')
  await expect(page.locator('#input-box')).toBeVisible()
  await page.locator('#input-box').fill('手动子节点')
  await page.locator('#input-box').press('Enter')
  await expect.poll(async () => (await get(request)).nodeCount).toBe(5)
  await expect(page.locator('#save-status')).toHaveText('已保存到本机')
  await page.locator('#undo').click()
  await expect.poll(async () => (await get(request)).nodeCount).toBe(4)
  await expect(root).toContainText('人工修改的主题')
})

test('external batch appears live, collapsed nodes update, and one undo rolls back the batch', async ({ page, request }) => {
  await page.goto('/')
  await expect(page.locator('[data-nodeid="mea"]')).toBeVisible()
  const changed = await edit(request, [
    { type: 'update_node', id: 'a1', patch: { topic: 'AI 更新隐藏节点' } },
    { type: 'add_node', parentId: 'b', node: { id: 'extra', topic: 'AI 新增观点' } },
  ])
  await expect(page.getByText('AI 新增观点', { exact: true })).toBeVisible()
  await expect(page.locator('[data-nodeid="mea1"]')).toHaveCount(0)
  expect(changed.data.nodeData.children[0].children[0].metadata.sources[0].quote).toBe('引用原文')
  await page.locator('#undo').click()
  await expect(page.getByText('AI 新增观点', { exact: true })).toHaveCount(0)
  expect((await get(request)).data.nodeData.children[0].children[0].topic).toBe('隐藏事实')
  await page.locator('#redo').click()
  await expect(page.getByText('AI 新增观点', { exact: true })).toBeVisible()
  await page.locator('[data-nodeid="mea"]').locator('..').locator('me-epd').click()
  await expect(page.getByText('AI 更新隐藏节点', { exact: true })).toBeVisible()
  await expect.poll(async () => (await get(request)).data.nodeData.children[0].expanded).toBe(true)
})

test('notes and provenance panel preserves existing metadata and multiple sources', async ({ page, request }) => {
  await edit(request, [{ type: 'update_node', id: 'b', patch: { metadata: { custom: 'keep', parent: { arbitrary: '保留任意扩展字段' }, sources: [{ document: '第一份.md' }, { document: '第二份.md', quote: '保留第二条' }] } } }])
  await page.goto('/')
  await page.locator('[data-nodeid="meb"]').click()
  await page.locator('#details-toggle').click()
  await expect(page.locator('#node-topic')).toHaveValue('实施方法')
  await page.locator('#node-note').fill('人工阅读笔记')
  await page.locator('#node-kind').selectOption('summary')
  await page.locator('#source-section').fill('第 2 节')
  await page.getByRole('button', { name: '保存节点详情' }).click()
  await expect.poll(async () => (await get(request)).data.nodeData.children[1].note).toBe('人工阅读笔记')
  const metadata = (await get(request)).data.nodeData.children[1].metadata
  expect(metadata.custom).toBe('keep')
  expect(metadata.parent.arbitrary).toBe('保留任意扩展字段')
  expect(metadata.sources[1].quote).toBe('保留第二条')
  expect(metadata.sources[0].section).toBe('第 2 节')
})

test('human editing concurrent with AI causes recoverable conflict, not an overwrite', async ({ page, request }) => {
  await page.goto('/')
  await page.locator('[data-nodeid="meb"]').dblclick({ delay: 70 })
  await page.locator('#input-box').fill('未提交的人工修改')
  await edit(request, [{ type: 'update_node', id: 'b', patch: { topic: '外部版本' } }])
  await expect(page.locator('#input-box')).toHaveText('未提交的人工修改')
  await page.locator('#input-box').press('Enter')
  await expect(page.locator('#notice')).toContainText('版本冲突')
  expect((await get(request)).data.nodeData.children[1].topic).toBe('外部版本')
  const download = page.waitForEvent('download')
  await page.locator('#reload-latest').click()
  await download
  await expect(page.locator('[data-nodeid="meb"]')).toContainText('外部版本')
  await expect(page.locator('#notice')).toBeHidden()
})

test('failed save survives reload as draft and can be restored', async ({ page, request }) => {
  await page.goto('/')
  await expect(page.locator('[data-nodeid="meroot"]')).toBeVisible()
  await page.route('**/api/document', route => route.request().method() === 'POST' ? route.abort() : route.continue())
  await page.locator('[data-nodeid="meb"]').dblclick({ delay: 70 })
  await page.locator('#input-box').fill('离线草稿')
  await page.locator('#input-box').press('Enter')
  await expect(page.locator('#notice')).toContainText('暂时不可用')
  expect((await get(request)).data.nodeData.children[1].topic).toBe('实施方法')
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await expect(page.locator('#notice')).toContainText('上次未保存')
  await page.unroute('**/api/document')
  await page.locator('#restore-draft').click()
  await expect.poll(async () => (await get(request)).data.nodeData.children[1].topic).toBe('离线草稿')
})

test('import validates before rendering; export and batch undo restore original IDs', async ({ page, request }) => {
  await page.goto('/')
  await expect(page.locator('[data-nodeid="meroot"]')).toBeVisible()
  const malformed = data()
  malformed.nodeData.children.push({ id: 'root', topic: '重复根节点' })
  await page.locator('#import-file').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(malformed)) })
  await page.locator('#import-confirm').click()
  await expect(page.locator('#notice')).toContainText('重复节点 ID')
  expect((await get(request)).nodeCount).toBe(4)
  const valid = { nodeData: { id: 'new-root', topic: '导入示例', children: [{ id: 'stable', topic: '保留 ID' }] }, direction: 2 }
  await page.locator('#import-file').setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(valid)) })
  await page.locator('#import-confirm').click()
  await expect(page.locator('[data-nodeid="menew-root"]')).toBeVisible()
  const downloaded = page.waitForEvent('download')
  await page.locator('#export').click()
  expect((await downloaded).suggestedFilename()).toBe('导入示例.mindmap.json')
  await page.locator('#undo').click()
  await expect(page.locator('[data-nodeid="meroot"]')).toBeVisible()
})

test('second browser receives human edits without an extra save loop', async ({ page, context, request }) => {
  await page.goto('/')
  const second = await context.newPage()
  await second.goto('/')
  await expect(second.locator('[data-nodeid="meb"]')).toBeVisible()
  const before = await get(request)
  await page.locator('[data-nodeid="meb"]').dblclick({ delay: 70 })
  await page.locator('#input-box').fill('跨窗口同步')
  await page.locator('#input-box').press('Enter')
  await expect(second.locator('[data-nodeid="meb"]')).toContainText('跨窗口同步')
  expect((await get(request)).revision).toBe(before.revision + 1)
  await second.close()
})

test('restoring a stale draft keeps its old base revision across a second reload', async ({ page, request }) => {
  await page.goto('/')
  await expect(page.locator('[data-nodeid="meb"]')).toBeVisible()
  await page.route('**/api/document', route => route.request().method() === 'POST' ? route.abort() : route.continue())
  await page.locator('[data-nodeid="meb"]').dblclick({ delay: 70 })
  await page.locator('#input-box').fill('旧版本草稿')
  await page.locator('#input-box').press('Enter')
  await expect(page.locator('#notice')).toContainText('暂时不可用')
  await edit(request, [{ type: 'update_node', id: 'b', patch: { topic: '必须保留的最新版本' } }])
  page.on('dialog', dialog => dialog.accept())
  await page.reload()
  await page.unroute('**/api/document')
  await page.locator('#restore-draft').click()
  await expect(page.locator('#notice')).toContainText('草稿基于旧版本')
  await page.reload()
  await page.locator('#restore-draft').click()
  await expect(page.locator('#notice')).toContainText('草稿基于旧版本')
  expect((await get(request)).data.nodeData.children[1].topic).toBe('必须保留的最新版本')
})

test('sample document: human note, AI supplement, reload, provenance and viewport fit', async ({ page, request }) => {
  const sample = JSON.parse(await readFile(resolve(import.meta.dirname, '../examples/城市绿地观察计划.mindmap.json'), 'utf8'))
  const doc = await get(request)
  expect((await request.post('/api/document', { data: { documentId: doc.documentId, baseRevision: doc.revision, requestId: randomUUID(), data: sample } })).ok()).toBeTruthy()
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await page.locator('[data-nodeid="meexample-method"]').click()
  await page.locator('#details-toggle').click()
  await page.locator('#node-note').fill('人工阅读笔记：每次记录观察时段和天气。')
  await page.getByRole('button', { name: '保存节点详情' }).click()
  await expect(page.locator('#save-status')).toHaveText('已保存到本机')
  await page.locator('#details-close').click()
  await edit(request, [{ type: 'add_node', parentId: 'example-limits', node: { id: 'example-question', topic: '待验证：增加季节覆盖', metadata: { kind: 'inference', sources: [{ document: '城市绿地观察计划.md', section: '5. 局限', quote: '天气、临时活动以及有限的观察时段都可能影响记录。' }] }, note: '由局限提出的后续研究问题，原文未承诺实施。' } }])
  await expect(page.locator('[data-nodeid="meexample-question"]')).toBeVisible()
  await page.reload()
  await expect(page.locator('[data-nodeid="meexample-question"]')).toBeVisible()
  const latest = await get(request)
  expect(latest.data.nodeData.children[1].note).toContain('人工阅读笔记')
  expect(latest.data.nodeData.children[1].metadata.sources[0].section).toBe('2. 观察方法')
  const bounds = await page.locator('me-tpc').evaluateAll(nodes => nodes.map(node => node.getBoundingClientRect().toJSON()))
  for (const rect of bounds) {
    expect(rect.top).toBeGreaterThanOrEqual(72)
    expect(rect.bottom).toBeLessThanOrEqual(920)
    expect(rect.left).toBeGreaterThanOrEqual(0)
    expect(rect.right).toBeLessThanOrEqual(1440)
  }
  const artifactDirectory = resolve(import.meta.dirname, '../artifacts')
  await mkdir(artifactDirectory, { recursive: true })
  await page.screenshot({ path: resolve(artifactDirectory, 'example-preview.png') })
})
